version: 2.1

parameters:
  region:
    type: string
    default: eu-west-1
  profile-name:
    type: string
    default: default
  role-arn:
    type: string
    default: "arn:aws:iam::446168904202:role/RoleForCircleCI"
  session-name:
    type: string
    default: circleci-session
  session-duration:
    type: string
    default: "300"

orbs:
  aws-cli: circleci/aws-cli@4.1.2

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.6.0

jobs:
  aws-setup:
    resource_class: small
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: << pipeline.parameters.profile-name >>
          role_arn: << pipeline.parameters.role-arn >>
          # optional
          role_session_name: << pipeline.parameters.session-name >>
          region: << pipeline.parameters.region >>
      - run:
          name: get-caller-identity
          command: |
            aws sts get-caller-identity --profile << pipeline.parameters.profile-name >>
      - persist_to_workspace:
          root: "~"
          paths: [.aws]
  plan-apply-module:
    resource_class: small
    executor: terraform
    steps:
      - attach_workspace:
          at: "~/.aws"
      - run:
          #working_directory: ./modules/setup-backend
          name: terraform plan
          command: |
            pwd
            ls -al
            terraform init
            terraform plan

workflows:
  plan-apply:
    jobs:
      - aws-setup:
          context: aws
      - plan-apply-module:
          requires:
            - aws-setup