version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  aws-example:
    environment:
      AWS_REGION: eu-west-1
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      # run the aws-cli/setup command from the orb
      - aws-cli/setup:
          role-arn: "arn:aws:iam::446168904202:role/RoleForCircleCI"
          aws-region: ${AWS_REGION}
          # optional parameters
          profile-name: "oidc-profile"
          role-session-name: "circle-session"
          session-duration: "300"
      - run:
          name: Log-into-AWS-ECR
          command: |
            aws ecr get-login-password --profile circle-session

workflows:
  OIDC-with-AWS:
    jobs:
      - aws-example:
          context: aws