version: 2.1

parameters:
  region:
    type: string
    default: eu-west-1
  profile-name:
    type: string
    default: default
  role-arn:
    type: string
    default: "arn:aws:iam::446168904202:role/RoleForCircleCI"
  session-name:
    type: string
    default: circleci-session
  session-duration:
    type: string
    default: "300"

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  aws-example:
    environment:
      AWS_REGION: eu-west-1
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: << pipeline.parameters.profile-name >>
          role_arn: << pipeline.parameters.role-arn >>
          role_session_name: << pipeline.parameters.session-name >>
          region: << pipeline.parameters.region >>
      - run:
          name: Log-into-AWS-ECR
          command: |
            aws ecr get-login-password --profile << pipeline.parameters.profile-name >>

workflows:
  OIDC-with-AWS:
    jobs:
      - aws-example:
          context: aws